# Assessment Model 

## General model specifications
The 2019 update stock assessment model was transitioned into SS version `r noquote(strsplit(o19$SS_version,";")[[1]][1])`, released 2019/03/09. Our transitioned model matched the time series of spawning biomass and stock depletion estimated in the 2019 stock assessment (light grey and dark grey lines, Figure \ref{fig:bridgingpanel}). The likelihoods between models were identical only when the natural mortality parameter for both sexes, and the descending standard error for both AKSLP and NWSLP survey age-based selectivities, were fixed to the values in the 2019 benchmark assessment (Table \ref{tab:bridgelike}). The base model presented here estimates parameters in the manner done in 2019, with the same priors. SS has a broad suite of structural options available for each application. There are no true `default' settings for most of these options; each application must be customized to best represent the life-history, dynamics, data-complexity, and estimation approach (Bayesian or maximum likelihood) most appropriate. 
After sequentially adding all new data, we freed the aforementioned parameters to produce a model which conformed to the Terms of Reference. The uncertainty in this model (which otherwise matches the structure of the 2019 benchmark assessment) was larger than the benchmark, which was not the case when the values for natural mortality were fixed. Importantly, this model was unable to satisfactorily fit to the composition data from the trawl fleet nor the WCGBTS survey (Figures \ref{fig:torafleet1agecomps}, \ref{fig:torafleet3agecomps}, and \ref{fig:torafleet8lencomps}), greatly overestimated the 2019 index, and distorted the recruitment patterns to suggest two large recruitment events since 2016 (Figure \ref{fig:torapanel}). 

During the exploration of recent data for this update assessment, modelers identified a large influx of younger, small fish observable in the age compositions of commercially landed catch, which was also visible in the discard length compositions of those commercial fleets (Figure \ref{fig:discard_lencomps}). This latter dataset was not used in the benchmark, nor were any commercial length compositions, due to conflicts between the age and length data. We rectify the lack of fit to the data by re-introducing the discard length compositions and time-blocking the retention curve to include a new block for the final two years of the model period (2019-2020; the benchmark model's terminal period for retention selectivity ran from 2011-2017). This adjustment resolved the aforementioned model fit issues (Figure \ref{fig:basepanel}). The proposed base model presented here otherwise estimates parameters in the manner done in 2019, with the same priors.

This stock assessment encompasses the U.S. West Coast and assumes a closed population. The first modeled year is 1890, the start of `r spp` landings in Washington. The population is assumed to be at equilibrium at the start of the modeling period because data from a full catch reconstruction for `r spp` back to the inception of the fishery is used to fit the model.
Fishery removals were divided among two fleets, (1) fixed gears and (2) trawl gears. Selectivity schedules are treated separately for each fleet. In the base model, retention parameters were fixed at values estimated from earlier exploratory model runs. Each trawl survey is treated as a separate survey with independently estimated selectivity parameters reflecting differences in depth and latitudinal coverage, survey design, methods, and equipment.

This assessment specifies sex with growth curves for males and females but tracks only the spawning biomass of females for calculating management quantities. Growth parameters describing the von Bertalanffy growth equation, as well as the spread of lengths for a given age, were estimated for each sex. The parameterization used for the estimation of growth by SS allows the user to specify the age for the two growth parameters (rather than the length at age zero and the implied length at infinite age). Ages 0.5 and 30 were selected to be close to the ranges found in the observed data. Sex-specific $M$ was estimated, with the informative priors based on the maximum aged fish in the composition data (102 years old for females from the fishery in 2006 and 91 years old for males from the survey in 2016).

Ages bins for the internal population dynamics range from 0-70 years, with the accumulator age of 70 specifying the plus group. This age was necessary to ensure that the plus group did not have a large number of fish.

Recruitment dynamics are governed by a Beverton-Holt stock-recruitment function. This relationship is parameterized to include two estimated quantities, the log of unexploited equilibrium recruitment ($R_0$) and steepness (relative recruitment at 20% of unfished spawning output; $h$). A full time-series of recruitment deviations, including the initial age-structure at the start of the model are estimated to adequately propagate uncertainty in the historical period and avoid imparting the perception of information through overly rigid conditions prior to the most recent time-period informed by length- and age-composition data. Sex-specific $M$ and selectivity can result in significant departures from equality for older ages due to differential $M$ and $F$ over age and sex.
Model files including the SS executable, data, control, starter, and forecast files are archived with the Pacific Fisheries Management Council.

The model calculates quantities using an annual time step. Thus, data collection is assumed to be relatively continuous throughout the year. Fishery removals occur instantaneously at the mid-point of each year and recruitment occurs on the 1st of January. The sex-ratio at birth is fixed at 1:1. 

### Priors
Uniform (non-informative) priors were applied to all estimated parameters in the base model with the exception of male and female $M$. Parameter bounds were identical to those used in 2019, which were selected to be sufficiently wide to avoid truncating the search procedure during maximum likelihood estimation. The base model fixed $h$ at `r model$parameters[grep('steep',model$parameters$Label),'Value']`. As with many assessments, this assessment is unable to estimate $h$, likely due to the largely one-way trip nature of the time-series during the period with good data collections and the high degree of confounding between population scale (via equilibrium recruitment), $M$, and $h$. Likelihood profiles for $h$ in past `r spp` assessments suggest that there is little information in the data to determine $h$. The use of a fixed value underestimates the uncertainty in $MSY$ and equilibrium yield. However, the importance of this reduced uncertainty is somewhat reduced because both and $F$ and $SB_{proxy}$ are used for management rather than $MSY$.

### Data weighting{#dw}

Sample weighting was used to achieve consistency between the degree of uncertainty in each data set and the fit of model estimates to those data. Variances and sample sizes were first derived from the raw data sources and then re-weighted using the Francis method ensure consistency between the input sample sizes (or standard errors) and the effective sample sizes (root mean square error, RMSE) based on model fit. This approach reduces the potential for particular data sources to have a disproportionate effect on total model fit, while creating estimates of uncertainty that are commensurate with the uncertainty inherent in the data.

In 2019, added variances for discard rates and mean body weights were set using values calculated iteratively using the RMSE of differences between input and estimated values derived from SS. Variances were parameterized in terms of standard deviation and coefficient of variation, respectively. We did not adjust nor re-calculate these values for the update assessment.

\begin{comment} For comparison, re-weighting using the Harmonic Mean method was applied to the length and age compositions (Figure \ref{fig:harmonicandfrancis}). Input sample sizes were based on the number of port-side samples, the number of observed trips, or the number of tows. Input sample sizes were multiplied by either a constant or an estimated parameter specific to each combination of data type (i.e., age or length) and fleet/survey. Multipliers enabled the mean input sample size to roughly equal the effective sample size based on model fit.

Variance estimates from the standardization of abundance information from the trawl surveys can be reasonably considered minimum estimates at best. Thus, an additive constant was freely estimated for each survey. Estimating additional variance components speeds the process of iterative re-weighting among data sources and propagates the uncertainty about the true survey index variance into the model results.

Added variances for discard rates and mean body weights were set using values calculated iteratively using the RMSE of differences between input and estimated values derived from SS. Variances were parameterized in terms of standard deviation and coefficient of variation, respectively. \end{comment}

Indices of relative abundance all had variance estimates generated as part of the analysis of raw catch data. These variances were converted to standard deviations in log space for use in the model; additional variances for the indices of abundance were estimated inside the model, except for the WCGBT Survey, for which the estimated added variance was near zero, so it was fixed at zero.

Additional variances were added to mean body weight of the fishery discard data as well as to the discard rates in a manner identical to those used in the 2019 assessment. The weighting of age- and length-composition data attempted to reduce the potential for particular data sources to have a disproportionate effect on total model fit, while creating estimates of uncertainty that were commensurate with the uncertainty inherent in the input data. 

Input age- and length-composition data were weighted via the Francis method (Table \ref{tab:torctorcw1}). Sensitivity to the iterative re-weighting approaches for developing consistency between the input composition sample sizes (or standard errors) and the effective sample sizes based on model fit using the Harmonic Mean (@McAllisterIanelli1997) and (@Francis2011) methods was completed. The Harmonic Mean method consisted of comparing the mean input sample size for compositional data with the mean effective sample size based on model fit. The Francis method considers the influence of compositional weights on fits to average lengths or average lengths-at-age. Generally, the Harmonic method suggested similar weights for the commercial length composition data, but placed more weight on the survey length data. It also indicated a downweighting of commercial age composition data compared to the 2019 benchmark, but to a lesser degree than the Francis approach (Figure \ref{fig:harmonicandfrancis}). 

During the Francis weighting process, several distinctions between this update and the weights used in the 2019 benchmark became apparent. Firstly, the 2019 benchmark assessment iteratively re-weighted both commercial fleet age composition weights to a maximum of one, whereas in this update (in the presence of commercial discard length compositions) they were downweighted by 90\% and 81\% (for fixed gear and trawl fleets, respectively, Table \ref{tab:torctorcw1}) . In addition, the WCGBTS length compositions were downweighted in the update by a factor of about 10 (from 0.29 in the benchmark to 0.033 in the present model), whereas the Triennial age compositions were upweighted by a factor of 10 (from 0.10 in the benchmark to a cap at 1.0 in the present model). We performed a sensitivity run where the Francis weights were fixed to the values used in 2019 and found the model to fit more poorly (Figure \ref{fig:harmonicandfrancis} and Table \ref{tab:torctorcw2}).

### Recruitment variation

The value of the parameter controlling recruitment variability was determined in 2019 using an iterative procedure with the aim of ensuring that the value of assumed by the assessment model and the empirical variance in recruitment were self-consistent. This involved setting to an initial value, fitting the model and calculating the variance of the recruitment deviations for the years for which recruitments are estimated, then replacing the assumed value of by the calculated value. The recruitment variability was tuned up to and capped at a value of 1.4, the maximum value at which the bias correction was expected to provide reliable results. This value was unchanged in this update assessment.

\begin{comment}

Data on $\sigma_R$ will never be precise, even in years with data. Therefore, the estimation of recruitment deviations exhibits a compromise between fitting information in the data and the central tendency to pull estimates of log(recruitment) deviations towards zero. Simulation results show that utilizing a bias-adjustment procedure can improve estimates of $\sigma_R$ (@MethotTaylor2011). Here, first the bias adjustment procedure within SS was updated to include the most recent data. Second, the RMSE of recruitment deviations was used to inform the $\sigma_R$, making the model internally consistent. $\sigma_R$ was capped at a value of 1.4, the point at which the bias correction is no longer expected to perform well (@MethotTaylor2011).
\end{comment}

### Estimated and fixed parameters
A total of `r nrow(model$parameters)` parameters were specified in the base model and `r max(model$parameters$Active_Cnt, na.rm = T)` of them were estimated (Tables \ref{tab:basepars} and \ref{tab:selparest}). Female and male $M$ were estimated, as is commonly done for groundfish stocks that exhibit dimorphic growth such as `r spp`. Time-invariant, sex-specific growth was also estimated.


### Natural mortality

From 1992 to 2007 a single fixed value for natural mortality ($M$) of 0.07 was assumed in all `r spp` stock assessments [@schirripa2007sablefish]. Improvements in the understanding of the importance of $M$ estimates on stock assessment model uncertainty, and the growing number of assessments identifying differences in $M$ among male and female groundfish, make a fixed value approach undesirable. Furthermore, the maximum aged `r spp` on record is over 100 years.
This assessment uses a prior probability distribution for males and females based maximum observed age (@then2015). Results of the analysis led to log-normal priors as follows: $ln(M)$ = $\langle$`r paste(round(model$parameters[grep('NatM',model$parameters$Label),c('Prior','Pr_SD')][1,],2), collapse=",")`$\rangle$ for females (@hamel2015icesjms) and $ln(M)$ = $\langle$`r paste(round(model$parameters[grep('NatM',model$parameters$Label),c('Prior','Pr_SD')][2,],2), collapse=",")`$\rangle$ for males (Figure \ref{fig:naturalmortalityprior}).

Both priors resulted in a substantial probability density over the range 0.02 to 0.12. The upper bound is higher than might be expected given that `r spp` are long-lived fish, but they also grow rapidly relative to most other long-lived fish.

### Unexploited Recruitment $R_0$

The log of the unexploited recruitment level, $ln(R_0)$, for the Beverton-Holt stock-recruitment function was estimated, as were annual recruitment deviations beginning at the model start, 1890. The main period of recruitment deviation estimation was chosen based on the first year of available sea-level data (i.e., `r min(model$cpue[model$cpue$Fleet_name == "ENV", "Yr"])`. The years in which mean bias was corrected for was based on methods developed by @MethotTaylor2011 that estimate the residual variability in the recruitment deviations for years in which data are available to inform the stock-recruitment curve. Survey catchability parameters were calculated analytically (set as scaling factors) such that the estimate is median unbiased, which is how $q$ is treated in most groundfish assessments approved by the Pacific Fisheries Management Council. Age selectivities were estimated using a double normal parameterization (SS pattern 24) for all fleets and surveys. The double normal allows for either dome-shaped or logistic selectivity, allowing for easy exploration of alternative selectivity assumptions. Sex-specific age selectivity was estimated for the fixed-gear fishery and the Triennial Shelf Survey because females are more selected to the gear than males. A single set of age selectivity parameters was estimated for females and males for the trawl fleet and all other surveys. 

### Selectivity and Retention

Initially, parameters for the width at the peak (P2) and initial selectivity (P5) were fixed at values that fit the data to allow for the estimation of dome-shaped selectivity. Dome-shaped selectivity was estimated by estimating the final selectivity parameters (P6) for all patterns except for the selectivities associated with the fixed-gear fleet and the WCGBT Survey, which was fixed based on a likelihood profile. The width of the descending limb parameters (P4) were estimated for all fleets except for the trawl fleet, which was fixed at the 2019 value. Surveys covering the shelf depths (WCGBT Survey and Triennial Shelf Survey) captured a large fraction of age-0 and age-1 `r spp`, with peak ages of the catch less at young ages ($\sim$\textless 2 years). Selectivity was lower for older individuals.

Time blocks for fishery selectivity and retention schedules were based on previous research with respect to influential management `milestones' and the recent introduction of catch shares within the trawl fishery (Table \ref{tab:tvretentionslxdates}). 
Milestones include:
\begin{enumerate}
  \item Full retention of age-1$^+$ `r spp` during WWII, rapid post-war fishery development, and introduction of trip-limit induced discarding (not just size-sorting) for the trawl fleet in 1982 and for fixed-gear fleets in 1997;
  \item A change in selectivity during the post-war groundfish fishery development in 2003 resulting from large scale movements of all fleets in response to large spatial closures (Rockfish Conservation Areas; RCAs); and
  \item Full retention all `r spp` within the trawl fishery with the implementation of the 2011 catch share program.
  \item \textit{New to this update assessment}: a time block in commercial retention for the final two years of the model (2019-2020) reflecting a change in discarding rates, responsive to a large influx of small recruits (particularly in the trawl fishery).
\end{enumerate}

\begin{comment}Parameters and time periods that indicated little change over time upon initial evaluation were not included in the base model.\end{comment} Length-based retention is defined for the commercial fishing fleets via a length-based logistic curve defined by an inflection, slope, and asymptote. The main retention curve parameters in the base model were fixed at values estimated in using models that fit to the discard length data. Ultimately, time-varying retention was implemented for the inflection and asymptote parameters for the fisheries to enable fitting of the discard-rate data. Full retention of small fish during World War II was assumed by fixing the inflection at 25 cm, implying retention of all fish greater than age-0. This inflection parameter was then permitted to vary through time. Full fishery retention was assumed prior to the institution of fishery trip limits (by fixing the asymptote parameter), then was permitted to vary until the most recent time period in the trawl fishery. Full retention in the time period from 2011-2018 was assumed in the trawl fishery due to the requirement of full catch accounting with the implementation of the catch shares program. The inflection point and asymptote for both the trawl and fixed-gear fishery retention curves were estimated in a final time block (2019-2020) to allow for increased discarding in those years. Peak fishery selectivity and the ascending limb of selectivity were permitted to vary among the time blocks for the fixed-gear fleet. The width of the descending limb of the trawl fleet was permitted to vary among the time blocks. Finally, time-varying selectivity was estimated using the descending limb of the Triennial Shelf Survey from 1995 forward to allow for changes in survey design.

### Discard Mortality

Discard mortality was assumed to be 100% for age-0 (less than 28 cm) `r spp` and decline rapidly to 20% for the fixed-gear fleet and 50% for the trawl fleet (for 29 cm and above, while splitting the difference at 28 cm). These values are consistent with those used by the Pacific Fisheries Management Council for management purposes.

## Changes made from 2019 Assessment

The salient changes to this update assessment versus the 2019 benchmark are as follows. Stopping at step 1 below produced the model that conformed to the Terms of Reference described in the executive summary, which failed to satisfactorily fit the data. To generate the base case model presented here, all three steps were taken.
\begin{enumerate}
\item Addition of recent information for all data sources which were included in 2019. Of these, we performed re-analyses for the WCGBTS survey (with data through 2019, see Section \ref{nwcbo}) and the environmental index of sea surface height (using tide-gauge information through 2020, see Section \ref{ssh}). 
\item Introduction of commercial discard length compositions from the West Coast Groundfish Observer Program (WCGOP) for 2002-2019 and 1986-1988 values from Pikitch, Erickson, and Wallace (1988). Input sample sizes for discard length compositions were based on the number of observed trips. 
\item Addition of a terminal time block for the two commercial fishery fleets from 2019-2020. Both the asymptote and inflection point are estimated for this time block for both fisheries; otherwise, the estimation structure for retention and selectivity parameters remains the same.
\end{enumerate}


## Base model selection and evaluation
All structural choices for stock assessment models are likely to be important under some circumstances. Therefore, these choices are generally made to  be as objective as possible and follow generally accepted methods of approaching similar models and data.
Sources of structural uncertainty in this assessment include:
\begin{enumerate}
\item the fixed value used for $h$,
\item  the fixed parameter values for the descending limb of dome shaped age selectivity in the fixed gear fleet (fixed by using likelihood profiles),
\item the assumption of a closed stock within the `r coast` Coast, and
\item the use of a time- and age-invariant (but sex-specific) $M$.
\item the assumption that the stock-recruit relationship follows a Beverton-Holt parameterization.
\end{enumerate}
In reality, unmodeled spatiotemporal variation in $M$, growth, and movement may impact `r spp` and the perception of the stock size and status. Predation, availability of food resources, or environmental factors may have directional instead of random effects on survival, growth, or movement during the modeled period. However, this degree of complexity is beyond the information content of the available data. Residual patterns in the length data could be due to unmodeled time-varying processes or reflect different growth trajectories among cohorts. `r Spp` along the `r coast` Coast do not exist independently of the population that occurs in British Columbia, Mexico to the south, and Alaskan waters to the north. The degree to which recruitment linkages and adult movement may be contributing to the observed dynamics of the U.S. West Coast stock is unknown. Potential shifts in spatial distribution in response to changes in density outside our waters or climate impacts could substantially reduce our ability to model and predict current and future trends. Efforts to synthesize existing data for northeast Pacific `r spp` with the aim of stock-wide modeling are underway.


