# Acknowledgments
This assessment draws heavily on the text and analyses in the 2019 and earlier assessments, and has benefited greatly from the efforts of all authors contributing to those analyses. Thanks to the instructors and members of the FISH 576/577 graduate course in Applied Stock Assessment at the UW School of Aquatic and Fisheries Science for their guidance. 

This assessment would not have been possible without the help of many people at various state and federal agencies who assisted in assembling the included data sources. Particularly, Beth Horness who provided survey data and Chantel Wetzel who wrote the data processing routine. Chantel Wetzel and Andi Stephens provided information regarding discard data. John Wallace provided assistance in extracting and processing various data sources. Richard Methot and Ian Taylor provided ongoing programming support and technical guidance in the use of Stock Synthesis. Kelli Johnson and Chantel Wetzel provided technical support for the `sa4ss` package which enabled document version control.
\begin{comment}
Additionally, the text you see here was improved by reviews provided by R1, R2. Ali Whitman, Tien-Shui Tsou, Melissa Mandrup, Ted Calavan, and Mark Freeman provided data and prompt responses to questions regarding its collection. Finally, we thank the STAR panel participants, John Field, Robin Cook, Yong Chen, Jim Ianelli, Patrick Mirick, Gerry Richter, John DeVore, and Stacey Miller, for their rigourous reviews and for facilitating the process. \end{comment}
