---
title: "extraData"
output: html_document
---

## NWCBO

\begin{comment}
VAST allows for the estimation of the variation in density for multiple locations across time and categories (e.g., species or age classes) and has been reviewed, endorsed, and recommended by the Pacific Fishery Management Council's Scientific and Statistical Committee for estimating abundance indices. Spatial and spatiotemporal variation is specifically included in both model components, i.e., encounter probabilities and positive catch rates, which are modeled using logit- and log-links, respectively. Gamma and log-normal error structures were investigated for the positive catch-rate component of the model to allow for skewness in the estimated distribution [@maunder2004fishresadjusting]. Vessel-year effects were included for each unique combination of vessel and year to account for the random selection of commercial vessels from those that were available [@helser_generalized_2004, @thorson_accounting_2014]. In summary, the survey biomass density (weight per area swept) was a function of year, latitude, longitude, and vessel-year. Spatial variation was approximated using 500 knots and the results were corrected for transformation bias @thorson_implementing_2016 using an algorithm in Template Model Builder @kristensen_tmb_2016. Further details regarding the structure of the spatiotemporal model available in VAST are available in the [https://github.com/James-Thorson-NOAA/VAST/tree/master/vignettes](user manual).

Specific details of how VAST was configured to estimate an index of abundance from WCGBT Survey data are available at[https://github.com /nwfsc-assess/VASTWestCoast](VASTWestCoast), which contains scripts specific to fitting VAST to data from surveys operating off of the U.S. West Coast. For example, a covariate was included for survey pass (i.e., 'first' or 'second') to account for the incomplete sampling during the second pass of the 2013 WCGBT Survey when the survey was cut short and no stations south of $37^\circ$N were sampled (Figure \ref{databyyearWCGBT3}) or seasonal, latitudinal movement.
\end{comment}
### Triennial Shelf Survey

Prior to the 2015 update, the Triennial Shelf Surveys conducted by the AFSC in 1980, 1983, 1986, 1989, 1992, 1995, 1998, and 2001 and by the NWFSC in 2004 provided the longest time series of information regarding abundance of `r spp`, especially for younger fish occurring at the shallowest depths (@weinberg2002noaa; Figure \ref{databyyearTriennial1}). Sampling occurred over depths from 55 to 366 m (500 m after 1992) and from $36.5^\circ$N ($34.5^\circ$N after 1992) to the Canadian border.
An estimated index was modeled using VAST. The parameterization differed from that used for the WCGBT Survey in the following two ways (see Appendix \ref{app:vast} for more details): no random component for vessel-year was included because it was estimated at zero and 250 knots were used for the spatial component. The estimated index shows an overall increase and an increase from 1995 to 2004 (Figure \ref{Triennialindexest}). However, the overall trend may not be reliable because of changes in timing, with the surveys occurring much earlier in 1995 and after, as well as movement of the survey into deeper waters between 1992 and 1995. To address this change in timing, `r spp` assessments since 2007 have estimated catchability separately for the two portions of the time-series. Q-Q plots suggested that the gamma distribution (Figures \ref{TriennialQQ} and \ref{QQhistTriennial}) fit the data, better than a log-normal distribution (results not shown). The highest densities for this survey were predicted off the coasts of Oregon and northern California (Figures \ref{surveydensTriennial1} - \ref{surveydensTriennial3}). No spatial or spatiotemporal patterns were found in the Pearson residuals (Figures \ref{surveyresid1Triennial1}-\ref{surveyresid2Triennial3}).
Lengths were collected for a large number of fish; however, age-sampling was relatively sparse (Table \ref{nafsctri}). Length compositions were variable and conspicuously missing age-0 fish in the early years of the survey (Figure \ref{Trienniallendat}). The age compositions show a truncated age structure (Figure \ref{Triennialagedat}) despite the survey sampling large individuals. This can be expected given the very limited depth range covered by the survey.

### Historical commercial landings
\begin{comment}
The historical commercial catch reconstruction used for this assessment is the same as that used in the last assessment for Oregon and California (Table \ref{catch.wide}; Figure \ref{catchstacked}). A new reconstruction was available from Washington that extended the catch history back to `r min(model$catch$Yr) + 1`. The most recent historical catches (from 1986 to present for Oregon and from 1981 to present for California and Washington) were extracted from Pacific Fisheries Information Network (PacFIN) during late February (26 Feb 2020).
For California, 1916--1968 commercial landings rely on estimates from the reconstruction efforts by the Southwest Fisheries Science Center and California Department of Fish and Game (CDFG; @ralston2010). Reconstructions utilized spatial information regarding groundfish landings back to 1931. This method is probably reliable for `r spp` because they are identified as a separate market category. Landings estimates for 1916-1931 were available from published CDFG Bulletins. Fisheries statistics of the U.S., published by the U.S. Fish Commission, extended the series back to 1908. Catch from 1908 was estimated to be less than 16 mt and was linearly extrapolated to zero in the first year of the model. The cumulative catch during this period was relatively small, and although there is uncertainty in apportionment to gear type, catches were split between fixed-gear and trawl fleets based on the earliest ratio recorded.
Oregon reconstruction efforts extend historical catches back to 1927 @karnowski2014. @low1976 provided total landings from 1915-1926. Information prior to 1915 remains undocumented. Thus, a linear extrapolation from 10 to 0 mt between 1915 and the first year of the model was applied.
Washington completed a historical catch reconstruction for this 2019 assessment (pers comm., Tien-Shui Tsou). These catches represent the best available landed catch information and are highly similar to the historical catches used in past `r spp` stock assessments. The following information sources were included in the reconstruction:

- 1890-1908: U.S. Fish Commission bulletin, 

-  1915-1952: PMFC bulletin 3, appendix (page 130, using a conversion factor of 1.75 for dressed fish), 
-  1953-1969: Washington Statistical bulletin, and

-  1970-1980: Washington fish ticket database. 
Catch area assignments were based on Seattle market reports and Washington Statistical bulletins. Gear type was based on PMFC bulletin 3 (page 44, Table 2) and Washington Statistical bulletins. During this reconstruction, it was found that catches during approximately 1935 to 1950 were slightly higher than those used previously because dressed fish were erroneously treated as whole fish rather than being expanded using the Washington Department of Fish and Wildlife (WDFW) conversion factor for that period.

### Foreign catches
Foreign catches are included in the state-specific reconstructions (Tables \ref{catch.wide} and \ref{app.table.catchbystate}) and were large in the late 1970s. Reconstructions for foreign catches were performed in 2007, based on records in the HAL data base and have since remained unchanged @lynde1986}.

### Fishery catch-per-unit-effort
Trawl fishery logbook data, collected by CDFG, Oregon Department of Fish and Wildlife, and WDFW, date back to the 1970s. Records provide tow-by-tow information regarding groundfish species including `r spp` The 1997 `r spp` assessment @crone1997sablefish} considered the use of a time series of standardized catch per unit effort (CPUE) based on the analyses described in Brodziak (1997), filtering the raw tow data for a 'deep-water' catch strategy (Dover, thornyheads, and `r spp`, i.e., DTS; @brodziak1997; @crone1997sablefish). Variable patterns were observed, and these were speculatively linked to management changes. Given the varied management history, inherent uncertainties associated with the use of fishery-dependent CPUE, and conflicting trends identified in earlier analyses, a commercial CPUE series has not been included in any recent `r spp` stock assessment. The topic was not revisited for this assessment.
Another potential source of fishery-dependent information is the bycatch of `r spp` in the mid-water whiting fishery @sampson1997. Anecdotal reports indicated that bycatch includes many small fish in years of above average recruitment. During the 2011 assessment, a preliminary investigation revealed that the length compositions from this source showed small fish associated with the 1999 and 2008 cohorts. Inclusion of these data (catch and length compositions) are included as a model  sensitivity.

\end{comment}

### Northwest Fisheries Science Center Slope Survey

The NWFSC Slope survey preceded the WCGBT Survey, starting in`r min(model$cpue[model$cpue$Fleet == 7, "Yr"])` and ending in `r max(model$cpue[model$cpue$Fleet == 7, "Yr"])`. The \Gls{s-wcgbt} is based on a random-grid design;However, the southern and shallow areas were not sampled during this survey as they are in the WCGBT Survey (Figure \ref{databyyearNWFSCSLP1}). The survey covered depths ranging from 183 - 1,280 m and used small (i.e., 93 ft) chartered commercial fishing vessels. This survey consists of fewer tows than the WCGBT Survey and the fraction of tows that sampled ages is much lower (Table \ref{nnwfscslope}).
VAST was used in a similar fashion to that specified for fitting the WCGBT Survey data to estimate a relative index of abundance. No random component for vessel-year was included for this survey. The estimated index shows a relatively flat trajectory over the survey period except for the increase in 2000 (Figure \ref{NWFSCSLPindexest}). Q-Q plots suggested that the gamma distribution (Figures \ref{NWFSCSLPQQ} and \ref{QQhistNWFSCSLP}) fit the data, better than a log-normal distribution (results not shown). The highest densities for this survey were predicted off of the coast of Oregon and northern California (Figures \ref{surveydensNWFSCSLP1} - \ref{surveydensNWFSCSLP2}) No spatial or spatiotemporal patterns were found in the Pearson residuals (Figures \ref{surveyresid1NWFSCSLP1}-\ref{surveyresid2NWFSCSLP3}). 
The length-compositions for the NWFSC Slope Survey showed the 1999 cohort as age-1, -2, and -3, but did not observe them at age-0 (Figure \ref{NWFSCSLPlendat}); this is expected because generally age-0 fish are present only over shallower depths. Dimorphic growth is visible in the data. The marginal age distributions corroborate the strong 1999 year-class and show some evidence for a strong 1995 cohort, as well as a protracted distribution of ages above age 10 (Figure \ref{NWFSCSLPagedat}).
### Alaska Fisheries Science Center Slope Survey
 \begin{comment} The parameterization differed from that used for the WCGBT Survey in the following three ways (see Appendix \ref{app:vast} for more details): no random component for vessel-year was included, 150 knots were used for the spatial component, and the encounter probability was fixed at one for any year where all tows encountered the species. The estimated index shows an increase from 1999 to 2001 (Figure \ref{AFSCSLPindexest}). Q-Q plots suggested that the gamma distribution (Figures \ref{AFSCSLPQQ} and \ref{QQhistAFSCSLP}) fit the data, better than a log-normal distribution (results not shown). The highest densities for this survey were predicted off the coast of Washington (Figure \ref{surveydensAFSCSLP1}). No spatial or spatiotemporal patterns were found in the Pearson residuals
(Figures \ref{surveyresid1AFSCSLP1} and \ref{surveyresid2AFSCSLP1}).
Similar to the NWFSC Slope Survey biological data, the length compositions for the AFSC Slope Survey show a strong 1999 cohort, a few age-0 fish in 2000 and 2001, and dimorphic growth (Figure \ref{AFSCSLPlendat}). The marginal age compositions are similar as well, with the exception of a seemingly anomalous number of males at the largest sizes (Figure \ref{AFSCSLPagedat}). \end{comment}


### Fishery biological data
\begin{comment}
Length compositions were aggregated without regard to sex, as was done in the previous assessment, to limit the exclusion of data and allow for a longer time series of length data than what would be available if all unsexed fish were removed (Table \ref{fisherycompn}). State-specific dorsal-to-fork length conversions were applied when appropriate. Sex-specific marginal age-compositions were calculated assigning unsexed fish to males and females using a 50:50 ratio. Generally, far more trips (and fish) have been sampled for length than for age (Table \ref{fisherycompn}), and the number of biological fishery samples is relatively small when compared to the sampling of other groundfish species. Year and fleet combinations with less than three tows were removed from the analysis.

Across time, length-compositions for each gear show differing distributions (Figure \ref{lcaggregate}). The fixed-gear fishery captures the broadest size spectrum (Figure \ref{lcaggregate}). The fixed-gear fishery retained almost no small fish (40 cm) in the early years (Figure \ref{fixlendat1} ), with small fish only being landed recently (Figure \ref{fixlendat2}). An apparent increase in the average size of fish caught by pots led to changes in the average length distribution landed by fixed gears between the late 2002 and roughly 2010. For the trawl fishery, the early years are quite variable due to small sample-sizes (Figure \ref{twllendat1}). This gear type appears to routinely land a much larger fraction of fish <40 cm, giving a very slight indication of the 1999, 2008, 2013, and 2015 cohorts as age-1 and age-2 fish (Figures \ref{twllendat1} and \ref{twllendat2}).

The WCGOP provided information regarding length-compositions of discarded `r spp` from 2002-2019. These samples were analyzed using a weighting method consistent with that applied to port samples described above. In aggregate, these samples reflect the sorting out of smaller fish from the retained catch, with all gears discarding `r spp` at age-1 and several observations of age-0 fish as well ( Figures \ref{fixlendat1}-\ref{twllendat2}).

Annual distributions from all fleets are highly variable due to limited sample sizes and probably only informative about the general size ranges that are discarded. It is important to note that all fleets have at some time discarded some `r spp` 50-60$^+$ cm in length. These fish are large enough to be valuable (and at least as large as the average retained \ `r spp`), implying that size-based sorting is not the only reason for discarding and that no size or age is likely to be completely retained under all conditions. With the implementation of the trawl catch share program, discarding is now directly accounted for and more than likely different than years prior to 2011.

In aggregate, generally more females are observed in the fishery age compositions than males (Figure \ref{acaggregate}); however, the male distributions contain relatively more of the oldest `r spp` (Figures \ref{lc48}-\ref{lc50b}). The annual fishery age distributions provide a reasonably clear picture of several prominent cohorts identified in other data sets despite the lack of very young fish. For example, the strong 2008 cohort can be tracked fairly clearly in both the male and female fixed-gear age compositions starting in 2010 as two year olds (Figures \ref{lc48} and \ref{lc48b}). The same is true for subsequent strong cohorts in 2013 and 2016. The fixed-gear fishery also shows evidence of a strong cohort beginning in the early 1990s (Figures \ref{lc48} and \ref{lc48b}). Age-composition data from the fixed-gear fishery is subject to more inter-annual variability, potentially attributable to spatial and depths changes in where the fishery was concentrated during different periods of time (anecdotally, the fishery operated in relatively deep water during the late 1980s when the oldest fish were observed). Tracking cohorts in the age data for the trawl fishery provides the clearest picture of the above-average year-classes common to all series because this sector has tended to retain the smallest fish of all sectors (Figures \ref{lc50} and \ref{lc50b}).
Also available from the WCGOP program were mean body weight observations from the discarded catch between 2002-2019. These were available for some hauls where length data were not collected. Fixed-gear annual body weight values were the larger than those from trawl gear (Figure \ref{bodywtfit}).
\end{comment}

### Biological Data

\begin{comment}
The estimation methods are described below.

### Weight-Length relationship
The weight-length relationship is based on the WCGBT Survey data collected from 2003 through 2019. Male and female curves were fit separately using the assumption of normally distributed residuals about the log-linear relationship $W = aL^b$. Parameter estimates derived from this analysis (Table \ref{biopars}) are consistent with published studies and previous `r spp` assessments. Estimated sex-specific relationships fit the data well and indicate little differences between males and females (Figure \ref{lc31}).

### Maturity schedule
Maturity is modeled as a logistic function of length, where the probability that individual $i$ is mature is based on the length of individual $i$ ($L_i$), length at 50\% maturity ($L_{50\%}$), and a rate parameter ($\beta$). Most studies report estimates of $L_{50\%}$, while fewer report estimates of $\beta$. Although several studies exist for Alaska, Canada, and the U.S. West Coast, the results are variable. In general, $L_{50\%}$ is greater for `r spp` in Alaska and Canada than off the U.S. West Coast @parks1983, mcfarlane1990}. Estimates of $L_{50\%}$ are smaller for `r spp` in deeper waters @fujiwara1988} and for older individuals @methot1994}; these latter effects are linked due to the likely ontogenetic movement of mature individuals offshore. Additionally, stressed individuals (such as those with tags) appear to have higher $L_{50\%}$ @mcfarlane1990}. In general, studies from similar areas @parks1987, parks1988}, time-frames @parks1983}, and designs @mcfarlane1990} estimate considerable variability in $L_{50\%}$. Variability could represent sampling error or variability in the biological processes influencing maturity, or both. In aggregate, variability among areas, years, and studies appears to represent a range of 2-4 cm between lower and upper estimates of $L_{50\%}$.

Historical estimates of $L_{50\%}$ for female `r spp` off the U.S. West Coast range from approximately 56 cm @parks1983, fujiwara1988, methot1994} to 60 cm @hunter1989}. @fujiwara1988} report an estimate of 0.13 for $\beta$. A recent study, which included 477 female `r spp`, found $L_{50\%}$ to decrease from north to south and with increasing depth (Head et al. 2014). Coast-wide estimates of $L_{50\%}$ were somewhat smaller than historical estimates at 54.64 cm. Here, we used a combination of data published during 2014 as well as additional coast wide samples collected and analyzed between 2014 and 2019 by NWFSC staff (pers. comm., M. Head), $L_{50\%}$ = ` r model$MGparmAdj$L_at_Amin_Fem_GP_1[model$MGparmAdj$Yr == 2019]` cm (Table \ref{biopars}) and $\beta$ = `r model$MGparmAdj$Mat_slope_Fem_GP_1[model$MGparmAdj$Yr == 2019]`. The maturity schedule suggests a slightly more protracted size range over which `r spp` mature than has been estimated in recent assessments (Figure \ref{lc32}).

### Fecundity
Available data suggests that `r spp` are determinate spawners (i.e., total oocytes at the beginning of the spawning season is equivalent to total annual spawning output) and spawn 3-4 times per year @hunter1989, @macewicz1994}. The total number of oocytes at the beginning of the spawning season appears to be linearly proportional to weight @hunter1989}, implying that spawning output for a mature female is also proportional to weight. This assumption has been used in previous `r spp` stock assessments and is retained here (Table \ref{biopars}) in the absence of new information. Data on skipped spawning are unavailable, as are data on environmental effects or other factors that could cause fecundity to vary nonlinearly with weight.

### Growth

\begin{comment}
Female `r spp` generally reach larger sizes and older ages than males. For example, a female `r spp` can grow larger than 100 cm and have a maximum age greater than 100 years old, while the largest and oldest male `r spp` observed was about 90 cm and 90 years old, respectively. However, relatively few `r spp` reach these large sizes and old ages. Estimates of the maximum size of `r spp` in the California Current have declined since the 1980s, likely due to both sustained fishing pressure over time and the use of the early pot survey data that selected larger and older fish to fit growth curves. For example, survey data used in the 1988 assessment were from the 1983 and 1985 pot surveys that selected larger and older fish, leading to von Bertalanffy estimates of asymptotic length of 77.5 cm for females and 64.5 cm for males. Subsequent assessments resulted in a decline in the estimated maximum size as more size-at-age data from other surveys and fisheries were included. For example, growth in the 2005 assessment estimated asymptotic length at 66.2 cm (females) and 55.8 cm (males). The most recent assessment produced similar estimates (Table \ref{tab.growthstudies}).

### Ageing bias and imprecision
Observed `r spp` ages are derived from visually counting rings on otoliths using 'break-and-burn' methods. These counts can be large because `r spp` are long-lived and the reproducibility of individual age estimates is imperfect, especially for older fish. Age-reading staff have indicated that `r spp` can be difficult to age. The observed age can differ (sometimes substantially) from the true age of a fish (i.e., 'reading error'). Aging error can be decomposed into the difference between true age and average-read age (bias) and variability around that average read age (precision). The bias and precision for aging methods or labs for west coast groundfish is estimated as a hierarchical model using readily available software @punt2008} and data consisting of comparisons among and within methods or labs ('cross-reads' or `double-reads').
A large number of double age reads were available for estimating `r spp` age error, thousands of samples, including a large number of reasonably old (\textgreater 40 years) `r spp` (Figures \ref{age_HistData}-\ref{age_Error}). While `r spp` lack a true age validation study, data from the AFSC include   30 individuals with known ages (i.e., no bias and perfect precision), with most fish   age 20, obtained from tag-recapture studies in Alaska. Between laboratory reads from the NWFSC, AFSC, Alaska Department of Fish and Game, and Fisheries and Oceans Canada were also available. The age-error analyses pooled samples within a laboratory, estimating a single vector of precision and bias across the age bins.
In 2011, initial inspection of the data revealed that NWFSC ages were biased (low) by one to three years relative to the small sample of tagged fish, which appeared to be aged more accurately by the AFSC. Data were then analyzed using the ageing-error model from @punt2008}, which estimates (1) the true proportion-at-age in the sample and (2) the bias and precision for each of four laboratories. This model treats the `true' age for each otolith as a random effect and estimates the marginal likelihood of all other fixed effects while integrating across these random effects. Stepwise (i.e., forward and backward) model selection was used to select among all combinations of three precision models (i.e., linear and a Holling's-form for either standard deviation or coefficient of variation for precision) and two bias models (i.e., linear or Holling's-form) for each laboratory, as well as the maximum age for which a proportion-at-age parameter was estimated (possibly ranging from 2 to 80 years).
Model comparisons were conducted using the Akaike Information Criterion. Stepwise model selection identified a model with Holling's-form bias and Holling's-form standard deviation of precision for each laboratory. Biases were very large and negative (i.e., reads were lower than the true age) and the standard deviation was increasing with true age for all laboratories (Figure \ref{age_DoubleReadData}). Initial modeling during the 2011 assessment suggested that ages were both highly imprecise and very biased. However, these model runs suggested that the degree of bias estimated from initial ageing error analyses was incompatible with observed cohorts moving through the population and produced poor residual patterns and unrealistically low estimates of natural mortality. Based on these findings the information used to estimate ageing error properties was re-evaluated.
The 2011 comparison of the larger sample of otoliths, containing older fish, collected during trawl survey operations revealed that there was likely a much greater consistency among labs for west coast fish (Figure \ref{age_HistData}). It was concluded that the `perfect' ages derived from the tagging experiment were not broadly representative of the aging methods for the fishery and survey samples available and that the initial analysis of bias was heavily influenced by these few fish. Therefore, the 2011 assessment estimated age error using only the NWFSC double-reads. This analysis assumed that the ages were unbiased but estimated the age imprecision such that by age 50 observed ages could differ from true ages by up to 11-12 years (Figure \ref{age_Error}).
The age error analysis for this assessment used the same software and methods as the 2011 assessment. Given that a large number of between lab reads from the AFSC and the NWFSC were available for this assessment, this age error analysis uses the between laboratory reads for the AFSC and NWFSC as well as the double reads from the NWFSC and treats both AFSC and NWFSC ages as unbiased but potentially non-linearly variable. The age imprecision was such that by age 50 observed ages could differ from true ages by up to 16-17 years (Figure \ref{age_Error}).

\end{comment}
